name_developer: "Hà Văn Đức"
nick_name: "Nhóc bang chủ 95"
home_town: "No.11, Cao Minh area, Xuân Diệu street, Kim Tân, Lào Cai city, Lào Cai"
address: "13 or 18 Floor, Keangnam Hanoi Landmark Tower, E6 Phạm Hùng street, Mễ Trì, Cầu giấy, Hà Nội"
year_old: "23 Year Old"
email: "ha.van.duc@framgia.com OR duchv2307@gmail.com (Primary email)"
phone: "0986 338 546"
fb_link: "https://www.facebook.com/nhocbangchu95"
github_link: "https://github.com/duchv2307"
linked_link: "https://www.linkedin.com/in/hà-văn-đức-919b72162"

per_page: 10
limit_deep: 5
take_post: 10
random: 3
